### PR TITLE
Supporting article (treating same as div)

### PR DESCRIPTION
**Pull request by adampash**

### CODE REVIEW

**Comment by xijo** [comment]
Hello @adampash , thanks for your PR. If the behaviour should be exactly like `div` I'd rather add it to the "div" behavior like `register :article, Div.new`. What do you think?

**Comment by xijo** [comment]
I added this in #7c7be1c. Please let met know if that's ok for you.

**Comment by adampash** [comment]
Makes sense to me! Thanks @xijo!

**Comment by xijo** [comment]
@adampash version 0.8.0 is released, including support for the `article` tag. Thanks again for contributing!

**Pull request closed without merging**
