### PR TITLE
Support strikethrough

### PR DESCRIPTION
**Pull request by fauno**
Hi! I've added strikethrough support, based on strong :)

### CODE REVIEW

**Comment by Sija** [comment]
`<del>` would be an alternative candidate :)

**Comment by fauno** [comment]
sure! should i add `<strike>` too? (it's deprecated since html4)

**Comment by xijo** [comment]
Thanks for your PR @fauno 

Did you see that there is already an implementation for strike through here: https://github.com/xijo/reverse_markdown/blob/master/lib/reverse_markdown/converters/del.rb

It's only enabled if you use the `ReverseMarkdown.config.github_flavored` option, since it's not part of the official markdown syntax. Please check it out and let me know what you think.

**Comment by fauno** [comment]
oooh i didn't notice it, sorry! so it would require to add `<s>` to the
list of tags it supports

**Comment by xijo** [comment]
Nevermind. I'll add `s` and close the PR, alright?

**Comment by fauno** [comment]
no problem, thanks!
-- 
:{

**Comment by xijo** [comment]
New version's released, thanks for the PR and I've included you in the changelog anyway 👍

**Pull request closed without merging**
